import { useEffect, useRef, useState } from "react";

/**
 * Renders the first page of a PDF onto a canvas with pdf.js.
 *
 * This replaces the flat `resume-preview.png` that used to sit here. That image
 * had to be regenerated by hand every time the PDF changed, and nothing enforced
 * it — so the dialog could advertise an old resume while the Download button
 * served a new one, silently. Drawing the PDF itself makes that class of drift
 * impossible: there is only one file now.
 *
 * It also keeps the reason the image existed in the first place. An <iframe> of
 * a PDF hands rendering to whatever viewer the browser supplies, which draws its
 * own scrollbar and — with the Acrobat extension installed — Adobe's toolbar, in
 * a process no stylesheet of ours can reach. iOS Safari declines to render
 * embedded PDFs at all. Here we are drawing pixels onto our own canvas, so there
 * is no foreign UI to hide and nothing to break on iOS.
 *
 * pdf.js is imported dynamically. It is by far the largest dependency in the
 * tree, and the dialog body only mounts when the dialog opens, so nobody pays
 * for it on first paint.
 */
export default function PdfPage({
  src,
  className = "",
  alt,
}: {
  src: string;
  className?: string;
  alt: string;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");

  useEffect(() => {
    let cancelled = false;
    // pdf.js hands back a task that must be cancelled if this unmounts
    // mid-render, or it draws onto a detached canvas and warns.
    let renderTask: {
      cancel: () => void;
      promise: Promise<void>;
    } | null = null;

    (async () => {
      try {
        const pdfjs = await import("pdfjs-dist");
        const workerSrc = (
          await import("pdfjs-dist/build/pdf.worker.min.mjs?url")
        ).default;
        pdfjs.GlobalWorkerOptions.workerSrc = workerSrc;

        // v6 takes a parameters object; the bare-string form was dropped.
        const doc = await pdfjs.getDocument({ url: src }).promise;
        if (cancelled) return;

        const page = await doc.getPage(1);
        const canvas = canvasRef.current;
        if (cancelled || !canvas) return;

        const context = canvas.getContext("2d");
        if (!context) return;

        // Render at the device's pixel density, then scale back down in CSS.
        // A canvas sized in CSS pixels renders soft on any retina display, and
        // this is a page of body-sized text — the one thing that must stay
        // legible for the preview to be worth showing at all.
        const dpr = Math.min(window.devicePixelRatio || 1, 2);
        const base = page.getViewport({ scale: 1 });
        const cssWidth = canvas.parentElement?.clientWidth ?? base.width;
        const scale = (cssWidth / base.width) * dpr;
        const viewport = page.getViewport({ scale });

        canvas.width = Math.floor(viewport.width);
        canvas.height = Math.floor(viewport.height);
        canvas.style.width = "100%";
        canvas.style.height = "auto";

        renderTask = page.render({ canvas, canvasContext: context, viewport });
        await renderTask.promise;
        if (!cancelled) setState("ready");
      } catch (err) {
        // A cancelled render rejects too; that is not a failure.
        if (!cancelled && (err as Error)?.name !== "RenderingCancelledException") {
          setState("error");
        }
      }
    })();

    return () => {
      cancelled = true;
      renderTask?.cancel();
    };
  }, [src]);

  return (
    <div className={`relative ${className}`}>
      <canvas
        ref={canvasRef}
        role="img"
        aria-label={alt}
        className={`block w-full transition-opacity duration-300 ${
          state === "ready" ? "opacity-100" : "opacity-0"
        }`}
      />

      {state === "loading" && (
        <div className="absolute inset-0 animate-pulse bg-white/[0.06]" />
      )}

      {/* A failed render must not leave an empty white box that reads as a
          broken page — the two actions below the preview still work, so say so
          rather than showing nothing. */}
      {state === "error" && (
        <div className="absolute inset-0 flex items-center justify-center bg-white/[0.04] px-6 text-center text-sm text-white/55">
          Preview unavailable — use Download or View in browser below.
        </div>
      )}
    </div>
  );
}
